# ---------------------------- #
#          Spongify            #
#         by SpongyCat         #
#    Discord: SpongyCat#1562   #
#    Thanks for downloading    #
#          the plugin!         #
# ---------------------------- #

# Tillable Mycelium
Mycelium_Tillable: true

# Auto Replant Enchant
Allow_Hoe_Crafting: true

# Compressed Crop
Allow_Compressed_Crafting: true

# Smelting Touch
Allow_Book_Crafting: true
Allow_Adding_Smelting_Enchant: true
Enable_Smelting_Touch: true

# Armor Stand with Arms
Enabled: true

# Bundle
Recipe_Enabled: true

# Command
# /spongify
Command_Enabled: true

# Mineral Arrowhead (%)
Diamond_Ore: 1
Ancient_Debris: 5