# ---------------------------- #
#          Spongify            #
#         by SpongyCat         #
#    Discord: SpongyCat#1562   #
#    Thanks for downloading    #
#          the plugin!         #
# ---------------------------- #

# Tillable Mycelium
Tillable_Mycelium:
  - Enable: true

# Auto Replant Enchant
Auto_Replant_Enchant:
  - Enable: true

# Compressed Crop
Compressed_Crops_Crafting: true

# Smelting Touch
Smelting_Touch:
  - Crafting: true
  - Allow_Adding_Enchant: true
  - Enable_Enchant: true

# Armor Stand with Arms
Armor_Stand_With_Arms: true

# Bundle
Allow_Bundle_Crafting: true

# Mineral Arrowhead (%)
Custom_Arrowhead:
  - Diamond_Ore: 1
  - Ancient_Debris: 5