name: Spongify
version: '${project.version}'
main: me.spongycat.spongify.Spongify
api-version: 1.19
load: STARTUP
authors: [SpongyCat]
description: Spongify Your World!
commands:
  lore:
    description: Add lore to your item.
    usage: /<command>
