name: Spongify
version: '${project.version}'
main: me.spongycat.spongify.Spongify
api-version: 1.19
load: STARTUP
authors: [SpongyCat]
description: Spongify Your World!
commands:
  spongify:
    description: All command for spongify.
    usage: /<command>
